<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\..\bin\Tests\Revit2020\$(Configuration)\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LicorpExportPlus.R20\LicorpExportPlus.R20.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="ricaun.RevitTest.TestAdapter" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>NUnit.Version</_Parameter1>
      <_Parameter2>2020</_Parameter2>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>NUnit.Open</_Parameter1>
      <_Parameter2>true</_Parameter2>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>NUnit.Close</_Parameter1>
      <_Parameter2>true</_Parameter2>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>NUnit.Language</_Parameter1>
      <_Parameter2>ENU</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>
</Project>
